/**
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge.ui.contentassist;

import de.upb.crypto.zeroknowledge.ui.contentassist.AbstractZeroKnowledgeProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ZeroKnowledgeProposalProvider extends AbstractZeroKnowledgeProposalProvider {
}
