/*
 * generated by Xtext 2.24.0
 */
package org.cryptimeleon.subzero.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.cryptimeleon.subzero.SubzeroRuntimeModule;
import org.cryptimeleon.subzero.SubzeroStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SubzeroIdeSetup extends SubzeroStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SubzeroRuntimeModule(), new SubzeroIdeModule()));
	}
	
}
