/**
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge;

import de.upb.crypto.zeroknowledge.AbstractZeroKnowledgeRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ZeroKnowledgeRuntimeModule extends AbstractZeroKnowledgeRuntimeModule {
}
