/**
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge.zeroKnowledge;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Witness Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.upb.crypto.zeroknowledge.zeroKnowledge.ZeroKnowledgePackage#getWitnessVariable()
 * @model
 * @generated
 */
public interface WitnessVariable extends Variable
{
} // WitnessVariable
