/*
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ZeroKnowledgeWebModule extends AbstractZeroKnowledgeWebModule {
}
