/*
 * generated by Xtext 2.24.0
 */
package org.cryptimeleon.zeroknowledge.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ZeroKnowledgeProposalProvider extends AbstractZeroKnowledgeProposalProvider {
}
