/**
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.upb.crypto.zeroknowledge.ZeroKnowledgeRuntimeModule;
import de.upb.crypto.zeroknowledge.ZeroKnowledgeStandaloneSetup;
import de.upb.crypto.zeroknowledge.ide.ZeroKnowledgeIdeModule;
import de.upb.crypto.zeroknowledge.web.ZeroKnowledgeWebModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class ZeroKnowledgeWebSetup extends ZeroKnowledgeStandaloneSetup {
  @Override
  public Injector createInjector() {
    ZeroKnowledgeRuntimeModule _zeroKnowledgeRuntimeModule = new ZeroKnowledgeRuntimeModule();
    ZeroKnowledgeIdeModule _zeroKnowledgeIdeModule = new ZeroKnowledgeIdeModule();
    ZeroKnowledgeWebModule _zeroKnowledgeWebModule = new ZeroKnowledgeWebModule();
    return Guice.createInjector(Modules2.mixin(_zeroKnowledgeRuntimeModule, _zeroKnowledgeIdeModule, _zeroKnowledgeWebModule));
  }
}
