/*
 * generated by Xtext 2.24.0
 */
package org.cryptimeleon.zeroknowledge;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ZeroKnowledgeStandaloneSetup extends ZeroKnowledgeStandaloneSetupGenerated {

	public static void doSetup() {
		new ZeroKnowledgeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
