/*
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link ZeroKnowledgeWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractZeroKnowledgeWebModule extends DefaultWebModule {

}
