/*
 * generated by Xtext 2.24.0
 */
package org.cryptimeleon.subzero;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SubzeroStandaloneSetup extends SubzeroStandaloneSetupGenerated {

	public static void doSetup() {
		new SubzeroStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
