/*
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge.ui;

import com.google.inject.Injector;
import de.upb.crypto.zeroknowledge.ui.internal.ZeroknowledgeActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ZeroKnowledgeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ZeroknowledgeActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ZeroknowledgeActivator activator = ZeroknowledgeActivator.getInstance();
		return activator != null ? activator.getInjector(ZeroknowledgeActivator.DE_UPB_CRYPTO_ZEROKNOWLEDGE_ZEROKNOWLEDGE) : null;
	}

}
