/*
 * generated by Xtext 2.17.0
 */
package de.upb.crypto.zeroknowledge


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ZeroKnowledgeRuntimeModule extends AbstractZeroKnowledgeRuntimeModule {
}
